### PR TITLE
Allowed labels for cronjobs, jobs, and changelog.

### PR DESCRIPTION
**Pull request by Strigix**
closes https://github.com/giantswarm/giantswarm/issues/28422

### CODE REVIEW

**Comment by Strigix** [comment]
closes https://github.com/giantswarm/giantswarm/issues/28422

**Comment by QuentinBisson** [comment]
Hey @Strigix have you tested it ?

**Comment by Strigix** [comment]
Not yet. 
To be honest, I wasn't sure how. 
The newest observe bundle hasn't got this version yet. Can I just edit the version of prometheus-operator-app? 
I was unsure because it was pushed to the catalog as kube-prometheus-stack-app. 
What would work best do you reckon?

**Comment by QuentinBisson** [comment]
Well i'm in a pickle. Is that for MCs or WCs as well?

**Comment by Strigix** [comment]
Oh, that was quite the late answer.
I believe this is mostly for MC's.

**Comment by QuentinBisson** [comment]
Then I would suggest you add it here https://github.com/giantswarm/config/blob/main/default/apps/observability-bundle/configmap-values.yaml.template instead like https://github.com/giantswarm/config/compare/main...Add-job-and-cronjob-labels?quick_pull=1

**Comment by QuentinBisson** [comment]
Maybe we still need this here :)

**Pull request closed without merging**
